### ISSUE TITLE
Cross-publish to 2.11 and 2.12

### ISSUE THREAD

**Issue by JD557** [regb/scalanative-graphics-bindings#3]
I noticed that this library is still compiled for scala 2.11 and 2.12 (https://github.com/regb/scalanative-graphics-bindings/blob/master/build.sbt#L4)

Would it be possible to publish those versions as well? Right now, it's only published for 2.13.

**Comment by regb** [comment]
Hello, sorry for the very long delay, but I finally got around and published the latest version for 2.11 and 2.12
